default_group_opssgm:
  gid: 46001
  name: opssgm
  priority_group: sgm
  accepted_voms_extensions: /alice/ROLE=
vars:
- 192.168.0.4
- 192.168.0.5
pool_accounts:
- base_name: alice
  initial_uid: '10417'
  users_num: '5'
  primary_group: alice
- base_name: sgmali
  initial_uid: '60101'
  users_num: '10'
  primary_group: alicesgm
  secondary_group: alice
- - base_name: dteam
    initial_uid: '18118'
    users_num: '10'
    primary_group: dteam
  - base_name: sgmdtm
    initial_uid: '60501'
    users_num: '5'
    primary_group: dteamsgm
    secondary_group: dteam
- - base_name: ops
    initial_uid: '45001'
    users_num: '10'
    primary_group: ops
  - base_name: sgmops
    initial_uid: '60701'
    users_num: '10'
    primary_group: ops
    secondary_group: opssgm
pbs_runtime_vars:
- lightweight_component02.cern.ch
- alice
default_group_ops_name: ops
site:
  name: simple-dev-site
  email: mayank.sharma@cern.ch
  latitude: 46.3
  longitude: 6.2
  location: CERN, Geneva, Switzerland
  description: A demo site demonstrating the SIMPLE framework for site setup
  website: https://home.cern
  support_website: https://groups.google.com/forum/#!forum/wlcg-lightweight-sites
  support_email: mayank.sharma@cern.ch
  security_email: mayank.sharma@cern.ch
  grid: wlcg
  tier: 3
  bdii_host: bdii.cern.ch
  use_argus: false
lightweight_components:
- lifecycle_hooks:
    pre_config:
    - /etc/simple_grid/lifecycle/ce_pre_config.sh
    pre_init:
    - /etc/simple_grid/lifecycle/ce_pre_inst1.sh
    post_init:
    - /etc/simple_grid/lifecycle/ce_post_inst1.sh
  name: Cream-CE
  deploy:
    node: lightweight_component01.cern.ch
    container_count: 1
  config:
    ce_si00: 381
    cream_db_password: str()
    cemon_host:
    - lightweight_component01.cern.ch
    ce_runtimeenv: EMI-3
    ce_close_se: SE3
    ce_cpu_vendor: Intel
    ce_minvirtmem: 8192
    ce_close_se3_access_point: /not/used
    batch_log_dir: /var/spool/pbs
    apel_db_password: str()
    ce_inboundip: false
    blparser_with_updater_notifier: true
    ce_logcpu: 0
    ce_os_arch: str()
    vo_sw_dir: /opt/exp_soft
    apel_mysql_host:
    - lightweight_component01.cern.ch
    ce_otherdescr: Cores=4
    cream_db_user: str()
    ce_sf00: 0
    ce_minphysmem: 2000
    ce_smpsize: 8
    ce_physcpu: 0
    ce_outboundip: true
    se_list:
    - not-used.some-domain
    blparser_host:
    - lightweight_component01.cern.ch
    globus_tcp_port_range:
      begin: 20000
      end: 21000
    ce_capability: CPUScalingReferenceSI00=1000
    mysql_password: fteu5746hg
    ce_cpu_model: Xeon
    ce_cpu_speed: 3000
    queues:
    - alice
    ce_close_se3_host: not-used.some-domain
    se_mount_info_list: none
  repository_revision: master
  repository_url: https://github.com/WLCG-Lightweight-Sites/wlcg_lightweight_site_ce_cream
  type: compute_element
  execution_id: 0
  preferred_tech_stack:
    level_2_configuration: yaim
  id: 0
- lifecycle_hooks:
    pre_config:
    - /etc/simple_grid/lifecycle/wn_pre_config.sh
    pre_init:
    - /etc/simple_grid/lifecycle/wn_pre_inst1.sh
    post_init:
    - /etc/simple_grid/lifecycle/wn_post_inst1.sh
  name: WN-Pbs
  deploy:
    node: lightweight_component02.cern.ch
    container_count: 1
  config:
    px_host: myproxy.cern.ch
    batch_server:
    - lightweight_component02.cern.ch
    ce_smpsize: 8
    ce_close_se3_access_point: /not/used
    ce_host:
    - lightweight_component02.cern.ch
    ce_close_se: SE3
    se_list: str() - *pbs_default_var_ce_close_se3_host
    ce_close_se3_host: not-used.some-domain
    se_mount_info_list: none
    vo_sw_dir: /opt/exp_soft
    queues:
    - alice
  repository_revision: master
  repository_url: https://github.com/WLCG-Lightweight-Sites/wlcg_lightweight_site_wn_pbs
  type: worker_node
  execution_id: 1
  preferred_tech_stack:
    level_2_configuration: yaim
  id: 1
default_group_dteamsgm:
  gid: 2680
  name: dteamsgm
  priority_group: sgm
  accepted_voms_extensions:
preferred_tech_stack:
  level_1_configuration: puppet
  level_2_configuration: puppet
  container_orchestration: docker-swarm
  container: docker
default_vo_generic_dn_server_secondary: /DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch
default_group_ops:
  gid: 45000
  name: ops
  accepted_voms_extensions:
default_group_alicesgm_name: alicesgm
default_pool_account_ops_with_sgm:
- base_name: ops
  initial_uid: '45001'
  users_num: '10'
  primary_group: ops
- base_name: sgmops
  initial_uid: '60701'
  users_num: '10'
  primary_group: ops
  secondary_group: opssgm
default_pool_account_dteamsgm:
  base_name: sgmdtm
  initial_uid: '60501'
  users_num: '5'
  primary_group: dteamsgm
  secondary_group: dteam
site_infrastructure:
- fqdn: lightweight_component01.cern.ch
  ip_address: 192.168.0.4
- fqdn: lightweight_component02.cern.ch
  ip_address: 192.168.0.5
default_group_alice_name: alice
default_vo_generic_dn_ca_cern: /DC=ch/DC=cern/CN=CERN Grid Certification Authority
supported_virtual_organizations:
- - name: alice
  - server: voms2.cern.ch
    port: '15000'
    dn: /DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch
    ca_dn: /DC=ch/DC=cern/CN=CERN Grid Certification Authority
  - server: lcg-voms2.cern.ch
    port: '15001'
    dn: /DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch
    ca_dn: /DC=ch/DC=cern/CN=CERN Grid Certification Authority
- - server: voms2.cern.ch
    port: '15001'
    dn: /DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch
    ca_dn: /DC=ch/DC=cern/CN=CERN Grid Certification Authority
  - server: lcg-voms2.cern.ch
    port: '15001'
    dn: /DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch
    ca_dn: /DC=ch/DC=cern/CN=CERN Grid Certification Authority
- - name: ops
  - server: voms2.cern.ch
    port: '15009'
    dn: /DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch
    ca_dn: /DC=ch/DC=cern/CN=CERN Grid Certification Authority
  - server: lcg-voms2.cern.ch
    port: '15009'
    dn: /DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch
    ca_dn: /DC=ch/DC=cern/CN=CERN Grid Certification Authority
default_vo_alice:
- name: alice
- server: voms2.cern.ch
  port: '15000'
  dn: /DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch
  ca_dn: /DC=ch/DC=cern/CN=CERN Grid Certification Authority
- server: lcg-voms2.cern.ch
  port: '15001'
  dn: /DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch
  ca_dn: /DC=ch/DC=cern/CN=CERN Grid Certification Authority
default_vo_generic_server_primary: voms2.cern.ch
default_vo_ops:
- name: ops
- server: voms2.cern.ch
  port: '15009'
  dn: /DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch
  ca_dn: /DC=ch/DC=cern/CN=CERN Grid Certification Authority
- server: lcg-voms2.cern.ch
  port: '15009'
  dn: /DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch
  ca_dn: /DC=ch/DC=cern/CN=CERN Grid Certification Authority
default_group_dteam:
  gid: 2688
  name: dteam
  accepted_voms_extensions:
default_pool_account_dteam:
  base_name: dteam
  initial_uid: '18118'
  users_num: '10'
  primary_group: dteam
groups:
- gid: 1395
  name: alice
  accepted_voms_extensions:
    vo: alice
    group: ''
    role: ''
    category: ''
- gid: 1397
  name: alicesgm
  priority_group: sgm
  accepted_voms_extensions: /alice/ROLE=lcgadmin
- gid: 2688
  name: dteam
  accepted_voms_extensions:
- gid: 2680
  name: dteamsgm
  priority_group: sgm
  accepted_voms_extensions:
- gid: 45000
  name: ops
  accepted_voms_extensions:
- gid: 2018
  name: opssgm
  priority_group: sgm
  accepted_voms_extensions: /alice/ROLE=
cream_runtime_vars:
- lightweight_component01.cern.ch
- alice
default_pool_account_dteam_with_sgm:
- base_name: dteam
  initial_uid: '18118'
  users_num: '10'
  primary_group: dteam
- base_name: sgmdtm
  initial_uid: '60501'
  users_num: '5'
  primary_group: dteamsgm
  secondary_group: dteam
default_vo_dteam:
- server: voms2.cern.ch
  port: '15001'
  dn: /DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch
  ca_dn: /DC=ch/DC=cern/CN=CERN Grid Certification Authority
- server: lcg-voms2.cern.ch
  port: '15001'
  dn: /DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch
  ca_dn: /DC=ch/DC=cern/CN=CERN Grid Certification Authority
default_pool_account_ops:
  base_name: ops
  initial_uid: '45001'
  users_num: '10'
  primary_group: ops
wn-pbs-expected-from-site-level-config:
  pbs_default_var_px_host: myproxy.cern.ch
  pbs_default_var_ce_host:
  - lightweight_component02.cern.ch
  pbs_default_var_ce_smpsize: 8
  pbs_default_var_batch_server:
  - lightweight_component02.cern.ch
  pbs_default_var_ce_close_se: SE3
  pbs_default_var_ce_close_se3_access_point: /not/used
  pbs_default_var_ce_close_se3_host: not-used.some-domain
  pbs_default_var_se_list: str() - *pbs_default_var_ce_close_se3_host
  pbs_default_var_se_mount_info_list: none
  pbs_default_var_vo_sw_dir: /opt/exp_soft
  pbs_default_var_queues:
  - alice
default_group_alice:
default_group_dteamsgm_name: dteamsgm
default_group_opssgm_name: opssgm
default_vo_generic_dn_server_primary: /DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch
cream-ce-expected-from-site-level-config:
  cream_default_var_globus_tcp_port_range:
    begin: 20000
    end: 21000
  cream_default_var_ce_capability: CPUScalingReferenceSI00=1000
  cream_default_var_ce_cpu_model: Xeon
  cream_default_var_ce_cpu_speed: 2800
  cream_default_var_ce_cpu_vendor: intel
  cream_default_var_ce_inboundip: false
  cream_default_var_ce_logcpu: 0
  cream_default_var_ce_minphysmem: 2000
  cream_default_var_ce_minvirtmem: 8192
  cream_default_var_ce_os_arch: x86_64
  cream_default_var_ce_otherdescr: Cores=4
  cream_default_var_ce_outboundip: true
  cream_default_var_ce_physcpu: 0
  cream_default_var_ce_runtimeenv: EMI-3
  cream_default_var_ce_sf00: 0
  cream_default_var_ce_si00: 381
  cream_default_var_ce_smpsize: 8
  cream_default_var_batch_log_dir: /var/spool/pbs
  cream_default_var_blparser_with_updater_notifier: true
  cream_default_var_blparser_host:
  - lightweight_component01.cern.ch
  cream_default_var_cemon_host:
  - lightweight_component01.cern.ch
  cream_default_var_cream_db_user: cream
  cream_default_var_apel_mysql_host:
  - lightweight_component01.cern.ch
  cream_default_var_ce_close_se: SE3
  cream_default_var_ce_close_se3_access_point: /not/used
  cream_default_var_ce_close_se3_host: not-used.some-domain
  cream_default_var_se_list:
  - not-used.some-domain
  cream_default_var_se_mount_info_list: none
  cream_default_var_vo_sw_dir: /opt/exp_soft
  cream_default_var_queues:
  - alice
default_vo_generic_server_secondary: lcg-voms2.cern.ch
default_pool_account_opssgm:
  base_name: sgmops
  initial_uid: '60701'
  users_num: '10'
  primary_group: ops
  secondary_group: opssgm
default_group_dteam_name: dteam
