---
expected-from-site-level-config:
    px_host: { type: str(), required: false, use_default: true}
    ce_host: { type: str(), required: false, use_default: true}
    ce_smpsize: { type: str(), required: false, use_default: true}
    batch_server: { type: str(), required: false, use_default: true}
    ce_close_se: { type: str(), required: false, use_default: true}
    ce_close_se3_access_point: { type: str(), required: false, use_default: true}
    ce_close_se3_host: { type: str(), required: false, use_default: true}
    se_list: { type: str(), required: false, use_default: true}
    se_mount_info_list: { type: str(), required: false, use_default: true}
    queues: { type: queue(), required: false, use_default: false}
